# sudo: required
service: 
  - docker

before_install:
  - docker build -t pohonets/docker-react -f Dockerfile.dev .

script:
  - docker run pohonets/docker-react npm run test -- --coverage

   # -e CI=true