version: 2.1
jobs:
  build:
    environment: 
      IMAGE_NAME: pohonets/docker-react
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest - f Dockerfile.dev .
      - run:
          name: Run tests 
          command: docker run -e CI=true $IMAGE_NAME:latest npm run test -- --coverage